blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/bklynali/BK-KSU/issues/1705
    about: "We do not accept external Feature Requests, see this link for more details."
